### ISSUE TITLE
 Signing transaction creation fails many times.

### ISSUE THREAD

**Issue by guarense** [bnogalm/StellarQtSDK#20]
I am creating new accounts with the library using msvc2015.
When I'm going to sign the creation transaction with the initial balance, sometimes the program is iced. This does not happen with payment transactions.

Account* account = new Account(founder, sequenceNumber);
Transaction* transaction = Transaction::Builder(account)
                         .addOperation(new CreateAccountOperation(targetDestination, "3"))
                         .build();
transaction->sign(founder); //<-Some time fails

When I use the test network to put the initial balance to the account that failed, it does not present a problem. Which is why I think the problem is in the signing of the creation operations.

**Comment by bnogalm** [comment]
i can try to build a test for it.

I think it can be the sequenceNumber, it use to be the common reason for failing transactions. Trace the value, and check when it fails what it should be.

In my wallet i always refresh the sequenceNumber before making any operation. It is also a nice to check destination account, as failing transaction have a cost.

(remember sequenceNumber is 64 bits, i forgot once for my wallet and i lost so much time getting crazy :S)

Other reason to fail is that the horizon instances use to have a limit of requests. If you make many they can ignore you for a while.

It is very strange if fails sometimes.

**Comment by guarense** [comment]
This simple code fail at signing. it is not a network problem
 
        KeyPair *source = KeyPair::fromSecretSeed(QString("SDKAAWHJTP7GETWHAJLXVVYNUVEV3ACB5AZHRS2B3BKSLNFIVCZH2FGX"));
        KeyPair *destination = KeyPair::fromAccountId(QString("GCWYQF2M4BYTWWVBKWSXJSO56BYTCMW2YD3BKOHW2L3UMZVSUZZ55HSZ"));

        qint64 sequenceNumber = 85173496447127;
        Account* account = new Account(source, sequenceNumber);
        Transaction* transaction = Transaction::Builder(account)
                .addOperation(new CreateAccountOperation(destination, "3"))
                .build();

        transaction->sign(source);
       qDebug()  << "Sign" << endl;

**Comment by bnogalm** [comment]
I just tried with mingw, it works, i will have a look with msvc.

That code to works requires a call to Network::useTestNetwork();  (or public network) but i guess you are already doing it.

I will definitely have a look at it, thanks for giving it a try :)

**Comment by bnogalm** [comment]
I tested it with msvc, It works running it multiple times (tested 100k)

Do you use multiple threads to sign the transactions?

Java implementation use exceptions, and i ported most of them, try to capture them or set the compiler to stop at exceptions.

**Comment by guarense** [comment]
Maybe its something in my computer. I will review any warning that may arise in my compilation to try to find out what may be causing this.

**Comment by guarense** [comment]
I am using openssl Lib and had to change the name of some fuctions at

 /external/ed25519/src/sha512.c 
/external/ed25519/src/sha512.h
/external/ed25519/src/verify.c
/external/ed25519/src/sign.c

because have de same name link reference in diferent .obj and i get error lnk2005

 int external_sha512_init(sha512_context * md);
int external_sha512_final(sha512_context * md, unsigned char *out);
int external_sha512_update(sha512_context * md, const unsigned char *in, size_t inlen);
int external_sha512(const unsigned char *message, size_t message_len, unsigned char *out);

The version in debug  runs fine and dont show problem

The version in release, cracks when i call a function with:
 new CreateAccountOperation(...)

**Comment by bnogalm** [comment]
Linkage mixup files with same name, even if they are in different paths.
There are linkage options to fix it but the easier is to change file names
and to make use of namespaces.

I didnt use openssl directly as for me was enough with Qt classes.

I will check it.

El 4 dic. 2018 16:22, "guarense" <notifications@github.com> escribió:

I am using openssl Lib and had to change the name of some fuctions at

/external/ed25519/src/sha512.c
/external/ed25519/src/sha512.h
/external/ed25519/src/verify.c
/external/ed25519/src/sign.c

because have de same name link reference in diferent .obj and i get error
lnk2005

int external_sha512_init(sha512_context * md);
int external_sha512_final(sha512_context * md, unsigned char *out);
int external_sha512_update(sha512_context * md, const unsigned char *in,
size_t inlen);
int external_sha512(const unsigned char *message, size_t message_len,
unsigned char *out);

The version in debug runs fine and dont show problem

The version in release, cracks when i call a function with:
new CreateAccountOperation(...)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/bnogalm/StellarQtSDK/issues/20#issuecomment-444138354>,
or mute the thread

**Comment by guarense** [comment]
I think openssl it is not the problem. I am calling the stellar sdk function from a QThread in a gui app. Making a little test outside the QThread and there is not any  crack. I will change my code and i will notify you what i find out

**Comment by guarense** [comment]
All is ok now.
